var zodiacs = [
{
	name: "Aries",
	month: "March 21-April 20"
	description: "Aries (♈︎) is the first astrological sign in the zodiac, spanning the first 30 degrees of celestial longitude (0°≤ λ <30°), and originates from the constellation of the same name. Under the tropical zodiac, the Sun transits this sign from approximately March 20 to April 21 each year.According to the tropical system of astrology, the Sun enters the sign of Aries when it reaches the March equinox, which occurs on average on March 21 (by design). Because the Earth takes approximately 365.24 days to go around the Sun, the precise time of the equinox is not the same each year, and generally will occur about six hours later from one year to the next until reset by a leap year. February 29 of a leap year causes that year's vernal equinox to fall about eighteen hours earlier—according to the calendar—compared with the previous year. This time duration is exactly the first month of the Solar Hijri calendar."
},
{
	name: "Taurus",
	month: "April 20 to May 20",
	description: "Taurus (♉︎) is the second astrological sign in the present zodiac. It spans from 30° to 60° of the zodiac. This sign belongs to the Earth element or triplicity, and has a feminine or negative polarity, as well as a fixed modality, quality, or quadruplicity. It is a Venus-ruled sign like Libra. The Moon has its exaltation here at exactly 3°. The Sun transits this sign from approximately April 21 until May 20 in western astrology."
},
{
	name: "Gemini",
	month: "May 21-June 20",
	description:"Gemini (♊︎)is the third astrological sign in the zodiac, originating from the constellation of Gemini. It is a positive mutable sign. Under the tropical zodiac, the sun transits this sign between about 21 May and 21 June.Gemini is represented by the twins Castor and Pollux, known as the Dioscuri. Taking from the twins that represent it, Gemini is considered by astrologists as one of the most important of the zodiacs since it captures someone's most basic 'levels.' For instance, it articulates their dual nature, a species with the so-called lower self and higher self as well as the way they are bilaterally symmetrical. Gemini is also considered by astrology followers as the most adaptable sign of the zodiac owing to the so-called mutable energy that allows individuals within this sign the so-called capability to view life from different angles."
},
{
	name: "Cancer",
	month: "June 21 - July 22",
	description: "Cancer (♋︎) is the fourth astrological sign in the Zodiac, originating from the constellation of Cancer. It spans from 90° to 120° celestial longitude. Under the tropical zodiac, the Sun transits this area between approximately June 22 and July 22, and under the sidereal zodiac, the Sun transits this area between approximately July 21 and August 9.In astrology, Cancer is the cardinal sign of the Water trigon, which is made up of Cancer, Pisces, and Scorpio. It is one of the six negative signs, and its ruling planet is the Moon. Though some depictions of Cancer feature a lobster or crayfish, the sign is most often represented by the crab, based on the Karkinos.Cancer is the fourth sign of the zodiac, which the sun enters at the summer solstice in the Northern Hemisphere, on approximately June 21. Those who are born from approximately June 21 to July 22 (depending upon the year) are born under Cancer. Individuals born during these dates, depending on which system of astrology they subscribe to, may be called 'Cancerians.' Cancer is a northern sign and its opposite sign is Capricorn.Cancer is a cardinal sign. Water is the element associated with Cancer, and, alongside Scorpio and Pisces, it forms the water trigon. The water trigon is one of four elemental trigons in the zodiac, with the other three being fire, earth, and air. When a trigon is influential, it is said to affect changes on earth. Cancer is said to be the house of Neptune and the exaltation of Jupiter, both astronomical bodies over those born under Cancer. Its ruling planet is the Moon."
},
{
	name: "Leo",
	month: "July 23-August 22",
	description: "Leo (♌︎) is the fifth astrological sign of the zodiac. It corresponds to the constellation Leo and comes after Cancer and before Virgo. The traditional Western zodiac associates Leo with the period between July 23 and August 22, and the sign spans the 120th to 150th degree of celestial longitude. Leo is associated with fire, and its modality is fixed. Under the tropical zodiac, the Sun transits this area on average between July 23 and August 22 each year, and under the sidereal zodiac, the Sun currently transits this area from approximately August 16 to September 15. The constellation Leo is associated with the mythological Nemean lion. Its opposite sign is Aquarius."
},
{
	name:"Virgo",
	month:"August 23- September 22",
	description: "Virgo (♍︎) is the sixth astrological sign in the Zodiac. It spans the 150–180th degree of the zodiac. Under the tropical zodiac, the Sun transits this area on average between August 23 and September 22, and the Sun transits the constellation Virgo from approximately September 16 to October 30. Individuals born during these dates, depending on which system of astrology they subscribe to, may be called Virgos or Virgoans; they are also represented in newspaper horoscopes with other astrological signs. The symbol of the maiden is based on Astraea. In Greek mythology, she was the last immortal to abandon Earth at the end of the Silver Age, when the gods fled to Olympus – hence the sign's association with Earth.The constellation Virgo has multiple different origins depending on which mythology is being studied. Most myths generally view Virgo as a maiden with heavy association with wheat. In Greek and Roman mythology, they relate the constellation to Demeter, mother of Persephone, or Proserpina, the Roman goddess of the harvest. Another association is with the myth of Parthenos (meaning virgin in Greek), which explains how the actual constellation Virgo came to be. In the legend, Parthenos is the daughter of Staphylus and Chrysothemis, and sister to Rhoeo and Molpadia. Rhoeo had been impregnated by Apollo, but when her father discovered her pregnancy, he assumed it was by a random suitor and was greatly ashamed. As punishment, he locked her in a box and threw her in a river. After the terrible fate of their sister, Parthenos and Molpadia lived in fear of their father's terrible wrath. One evening, Staphylus left his daughters in charge of a very valuable bottle of wine. When they both accidentally fell asleep, one of their swine broke the bottle. Terrified of their father, the sisters fled to a nearby cliff and threw themselves off. But because of his previous relations with Rhoeo, Apollo saved his two sisters and delivered them to the safety of nearby cities in Cherronseos. Molpadia ended up in Castabus where she changed her name to Hemithea and was worshipped as a local goddess for many years. Parthenos settled in Bubastus where she was also worshipped as a local goddess. According to another story, Parthenos was a daughter of Apollo who made the constellation to commemorate her death at a young age. While this is only one myth of the origin of Virgo, she is seen throughout all manner of myths. In Egyptian mythology, the time when the Sun was in the constellation Virgo marked the beginning of the wheat harvest, thus connecting Virgo back to the wheat grain. In Judeo-Christianity, Jesus was born to a virgin in the town of Bethlehem ("bread"); the ancient Zodiac ended in the constellation Leo and began with Virgo. Virgo has the equivalent sign in Indian astrology as the Kanya (which also means 'maiden'), and has even been connected with the Virgin Mary."
},
{
	name: "Libra",
	month: "September 23- October 22",
	description: "Libra (♎︎) is the seventh astrological sign in the Zodiac. It spans 180°–210° celestial longitude. The Sun transits this sign on average between September 23 (September equinox) and October 22. Under the sidereal zodiac, the Sun currently transits the constellation of Libra from approximately October 31 to November 22. The symbol of the scales is based on the Scales of Justice held by Themis, the Greek personification of divine law and custom. She became the inspiration for modern depictions of Lady Justice. The ruling planet of Libra is Venus. Libra is the only zodiac constellation in the sky represented by an inanimate object. The other eleven signs are represented either as an animal or mythological characters throughout history. Libra is one of the three zodiac air signs, the others being Gemini and Aquarius. In astrology, a broad description of those who are born under these signs are calm, rational, and detached when dealing with situations. The sign of Libra is symbolized by the scales and is associated with the Roman deity Iustitia. According to the writer Manilius, Roman judges are born under the sign of Libra."
},
{
	name:"Scorpio",
	month: "October 23- November 22",
	description: "Scorpio (♏︎) is the eighth astrological sign in the Zodiac, originating from the constellation of Scorpius. It spans 210°–240° ecliptic longitude. Under the tropical zodiac (most commonly used in Western astrology), the Sun transits this sign on average from October 23 to November 22. Under the sidereal zodiac (most commonly used in Hindu astrology), the Sun is in Scorpio from approximately November 16 to December 15. Depending on which zodiac system one uses, an individual born under the influence of Scorpio may be called a Scorpio or a Scorpion. Scorpio is one of the three water signs, the others being Cancer and Pisces. It is a fixed, negative sign. Scorpio is associated with three different animals: the scorpion, the snake, and the eagle (or phoenix). According to The Astrology Bible, Scorpio's colors are deep red, maroon, black, and brown."
},
{
	name: "Sagittarius",
	month: "November 23- December 22",
	description: "Sagittarius (♐︎) is the ninth astrological sign, which is associated with the constellation Sagittarius and spans 240–270th degrees of the zodiac. Under the tropical zodiac, the sun transits this sign between approximately November 23 and December 21. Greek mythology associates Sagittarius with the centaur Chiron, who mentored Achilles, a Greek hero of the Trojan War, in archery. Sagittarius, the half human and half horse, is the centaur of mythology, the learned healer whose higher intelligence forms a bridge between Earth and Heaven. Also known as the Archer, Sagittarius is represented by the symbol of a bow and arrow.Along with Aries and Leo, Sagittarius is a part of the Fire Trigon as well as the last of the reproductive trinity. It also follows Gemini and Virgo as third of the mutable signs, which are the signs that feature changeable quality. The image of the sign says much about its features: he is able to be extremely violent or wise, brave or mild.[citation needed] When Sagittarius is depicted as an archer, then he is classified as human but when represented as a centaur, he is nonhuman (bestial).[5] However, the classification of the astrological sign as a human or bestial does not carry practical consequences for interpretation. As an archer, Sagittarius is said never to fail in hitting the mark and this depiction alludes to the power of prophecy, hence, the claim that seers and prophets are born in this sign."
},
{
	name: "Capricorn",
	month: "December 21- January 19",
	description: "Capricorn (♑︎) is the tenth astrological sign in the zodiac out of twelve total zodiac signs, originating from the constellation of Capricornus, the horned goat. It spans the 270–300th degree of the zodiac, corresponding to celestial longitude. Under the tropical zodiac, the sun transits this area from about December 21 to January 21 the following year, and under the sidereal zodiac, the sun transits the constellation of Capricorn from approximately January 16 to February 16. In astrology, Capricorn is considered an earth sign, negative sign, and one of the four cardinal signs. Capricorn is said to be ruled by the planet Saturn. There appears to be a connection between traditional characterisations of Capricorn as a sea goat and the Sumerian god of wisdom and waters, Enki, who also had the head and upper body of a goat and the lower body and tail of a fish.[7] Later known as Ea in Akkadian and Babylonian mythology, Enki was the god of intelligence (gestú, literally "ear"), creation, crafts; magic; water, seawater and lakewater.In India, the zodiac sign of Capricorn is celebrated as the Makara Sankranti festival, also known in Nepal as Maghe Sankranti. The Indian astronomical calendar is not based on the western Gregorian or Julian date keeping system. The Gregorian calendar has fixed days in a year and does not accommodate difference in the actual solar year. Therefore, the festival is celebrated on either of 14 or 15 January every year, when, as per the Indian astronomical calendar, the Sun actually enters the Capricorn sign."
},
{
	name:"Aquarius",
	month: "January 20 - February 19",
	description: "Aquarius (♒︎) is the eleventh astrological sign in the Zodiac, originating from the constellation Aquarius. Under the tropical zodiac, the Sun is in the Aquarius sign between about January 21 and about February 20, while under the sidereal Zodiac, the sun is in Aquarius from approximately February 15 to March 14, depending on the leap year. Aquarius is a winter constellation in the northern hemisphere, found near Pisces and Cetus. It is especially notable as the radiant for four meteor showers, the largest of which is the Southern Delta Aquariids in late July and early August."
},
{
	name: "Pisces",
	month: "February 20 - March 20",
	description: "Pisces (♓︎) is the twelfth astrological sign in the Zodiac. It is a negative mutable sign. It spans 330° to 360° of celestial longitude. Under the tropical zodiac, the sun transits this area between February 19 and March 20. In sidereal astrology, the Sun currently transits the constellation of Pisces from approximately March 12 to April 18. In classical interpretations, the symbol of the fish is derived from the ichthyocentaurs, who aided Aphrodite when she was born from the sea. According to some tropical astrologers, the current astrological age is the Age of Pisces,[7] while others maintain that currently it is the Age of Aquarius.While the astrological sign Pisces per definition runs from ecliptic longitude 330° to 0°, this position is now mostly covered by the constellation of Aquarius due to the precession from when the constellation and the sign coincided. Today, the First Point of Aries, or the vernal equinox, is in the Pisces constellation. There are no prominent stars in the constellation,with the brightest stars being of only fourth magnitude. One star in the constellation, Alpha Piscium, is also known as Alrescha, which comes from the Arabic الرشآء al-rišā’, meaning 'the well rope,'or 'the cord.' The constellation, however, is different from the astronomical location in where the sign occupies space. The constellations in earlier times were primarily used as markers to help determine what influence was in the sky. Nevertheless, the sign of Pisces remain in the 30 degree span of 330°-0°."
},	
}